2020-04-25 12:20:23,423 ERROR Bigflow.Core.models tuple index out of range
2020-04-25 12:20:23,431 WARNING django.request Not Found: /pr_approve/
2020-04-25 12:20:29,037 ERROR django.request Internal Server Error: /purchasesmryget/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vsolv/Desktop/Project/Python/Bigflow/Bigflow/Purchase/views.py", line 412, in purchasesmryget
    Emp_gid = decry_data(request.session['Emp_gid'])
  File "/home/vsolv/Desktop/Project/Python/Bigflow/Bigflow/Core/models.py", line 194, in decrpt
    data = hashid[0]
IndexError: tuple index out of range
2020-04-25 12:20:35,220 ERROR Bigflow.Core.models tuple index out of range
2020-04-25 12:20:35,226 WARNING django.request Not Found: /commodity/
2020-04-25 12:21:26,528 WARNING django.request Not Found: /{{viewfilepath}}
2020-04-25 12:21:26,585 WARNING django.request Not Found: /{{prheader_imagepath}}
